root: ./

​structure:  
    readme: README.md

redirects:
    umbraco-cms/fundamentals/setup/upgrading/general: umbraco-cms/fundamentals/setup/upgrading/README.md
    umbraco-cloud/set-up/manage-hostnames/rewrites-on-cloud: umbraco-cloud/set-up/project-settings/manage-hostnames/rewrites-on-cloud.md
    umbraco-cloud/set-up/manage-security: umbraco-cloud/set-up/project-settings/manage-security.md
    umbraco-cloud/set-up/manage-cdn-caching: umbraco-cloud/set-up/project-settings/manage-cdn-caching.md
    umbraco-cloud/set-up/external-services: umbraco-cloud/set-up/project-settings/external-services.md
    umbraco-cloud/set-up/dedicated-resources: umbraco-cloud/set-up/project-settings/dedicated-resources.md
    v/workflow: umbraco-workflow/README.md
