root: ./

​structure:  
    readme: README.md
    summary: SUMMARY.md

installing-deploy/installing-deploy: getting-started/install-configure.md
installing-deploy/install-configure: getting-started-install-configure.md
installing-deploy/install-configure/existing-site: getting-started/install-configure.md
installing-deploy/install-configure/new-site: getting-started/install-configure.md
installing-deploy/cicd-pipeline: getting-started/cicd-pipeline/README.md
installing-deploy/cicd-pipeline/ci-cd-azure-dev-ops: getting-started/cicd-pipeline/ci-cd-azure-dev-ops.md
installing-deploy/cicd-pipeline/ci-cd-github-actions: getting-started/cicd-pipeline/ci-cd-github-actions.md
installing-deploy/streamlining-local-development: getting-started/streamlining-local-development


