extends: conditional
message: "'%s' has no definition"
level: error
scope: text
ignorecase: false
# Ensures that the existence of 'first' implies the existence of 'second'.
# Require leading whitespace to avoid matching on URL substrings eg https://www.youtube.com/embed/OUD-PbWESAs?rel=0
first: '\s\b([A-Z]{3,5})\b'
second: '([A-Z]{3,5}): (?:\b[A-Z][a-z]+ )+|(?:\b[A-Z][a-z]+ )+\(([A-Z]{3,5})\)'
# ... with the exception of these:
exceptions:
    - ABC
    - ADD
    - ALT
    - HTML
    - JSON
    - CSS
    - API
    - URL
    - UDI
    - URI
    - NET
    - MVC
    - GET
    - ASP
    - ADO
    - REST
    - HTTP
    - HTTPS
    - CURL
    - BASE
    - UDA
    - CLI
    - KUDU
    - XML
    - PATH
    - SQL
    - SHIFT
    - POST
    - GUID
    - UWP
    - HAL
    - LINK
    - DLL
    - CMS
    - ONLY
    - IIS
    - DNS
    - DOM
    - XSLT
    - AJAX
    - YAML
    - PNG
    - ISO
    - PDF
    - DXP
    - FAQ
    - DIBS
    - VAT
    - SKU
    - UTC
    - HEX
    - RGBA
    - IDE
    - CPU
    - RAM
    - CNAME
    - AAAA
    - TXT
    - PUT
    - DELETE
    - ZIP
    - CTRL
    - SPACE
    - ENTER
    - VIP
    - DEBUG
    - INFO
    - TEMP
    - GIF
    - GDPR
    - NPM
    - SVG
    - DHL
    - UUI
    - MDN
