extends: existence
message: "Start each option with a capital letter."
link: https://github.com/testthedocs/vale-styles/blob/master/OpenStack/ListStart.yml
level: warning
scope: list
nonword: true
tokens:
  - '^[a-z].+'