extends: substitution
message: "We prefer %s over '%s'"
level: warning
swap:
  '(?:(?<!\.)css)' : CSS
  '(?:(?<!\.)[hH]tml)' : HTML
  url: "'URL'"
  '(?:(?<!\.)js|[jJ]ava[sS]cript)' : JavaScript
  .net: "'.NET'"
  dot net: "'.NET'"
  cms: "'CMS'"
  '[aA]ngular[jJ][sS]' : AngularJS
