---
extends: substitution
message: "We prefer %s over '%s.'"
level: warning
ignorecase: true
swap:
  blacklist: "'deny list'"
  whitelist: "'allow list'"
  black list: "'deny list'"
  white list: "'allow list'"  
  master: "'primary'"
  slave: "'secondary'"
  etc.: "'and so on'"
  \b(?:eg|e\.g\.)[\s,]: "'for example'"
  \b(?:ie|i\.e\.)[\s,]: "'that is'"
