root: ./

​structure:  
    readme: README.md
    summary: SUMMARY.md

redirects:
    configuration: getting-started/configuration.md
    dashboards-and-buttons: getting-started/dashboards-and-buttons.md
    notifications: getting-started/notifications.md
    workflow-content-app: getting-started/workflow-content-app.md
    upgrading-workflow/upgrading-workflow: upgrading-workflow/upgrading.md
    workflow-section/workflow-section: workflow-section/workflow-section-dashboard.md